//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamaManager.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GamaManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add friend.
        /// </summary>
        public static string addFriendDialogTitleContent {
            get {
                return ResourceManager.GetString("addFriendDialogTitleContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Attention.
        /// </summary>
        public static string attentionLabelContent {
            get {
                return ResourceManager.GetString("attentionLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на suspended.
        /// </summary>
        public static string audioStatePausedLabelContent {
            get {
                return ResourceManager.GetString("audioStatePausedLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на now playing.
        /// </summary>
        public static string audioStatePlayingLabelContent {
            get {
                return ResourceManager.GetString("audioStatePlayingLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Back.
        /// </summary>
        public static string backBtnContent {
            get {
                return ResourceManager.GetString("backBtnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string cancelBtnContent {
            get {
                return ResourceManager.GetString("cancelBtnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About.
        /// </summary>
        public static string editProfileAboutLabelContent {
            get {
                return ResourceManager.GetString("editProfileAboutLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit profile.
        /// </summary>
        public static string editProfileBtnContent {
            get {
                return ResourceManager.GetString("editProfileBtnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Country.
        /// </summary>
        public static string editProfileCountryLabelContent {
            get {
                return ResourceManager.GetString("editProfileCountryLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt;&gt; Edit profile.
        /// </summary>
        public static string editProfileLabelContent {
            get {
                return ResourceManager.GetString("editProfileLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Location.
        /// </summary>
        public static string editProfileLocationLabelContent {
            get {
                return ResourceManager.GetString("editProfileLocationLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Main info.
        /// </summary>
        public static string editProfileMainInfoLabelContent {
            get {
                return ResourceManager.GetString("editProfileMainInfoLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Profile name.
        /// </summary>
        public static string editProfileNameLabelContent {
            get {
                return ResourceManager.GetString("editProfileNameLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        public static string errorLabelContent {
            get {
                return ResourceManager.GetString("errorLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exit.
        /// </summary>
        public static string exitBtnContent {
            get {
                return ResourceManager.GetString("exitBtnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You are about to exit the Office ware game manager. You&apos;ll need to re-enter&amp;#10;your username and password in order to log back into Office ware Game Manager..
        /// </summary>
        public static string exitDescLabelContent {
            get {
                return ResourceManager.GetString("exitDescLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exit.
        /// </summary>
        public static string exitLabelContent {
            get {
                return ResourceManager.GetString("exitLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Friends and chat.
        /// </summary>
        public static string friendsAndChatLabelContent {
            get {
                return ResourceManager.GetString("friendsAndChatLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Friends.
        /// </summary>
        public static string friendsLabelContent {
            get {
                return ResourceManager.GetString("friendsLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add friend.
        /// </summary>
        public static string friendsMenuItemAddFriendLabelContent {
            get {
                return ResourceManager.GetString("friendsMenuItemAddFriendLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Friends.
        /// </summary>
        public static string friendsMenuItemLabelContent {
            get {
                return ResourceManager.GetString("friendsMenuItemLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  from .
        /// </summary>
        public static string fromLabelContent {
            get {
                return ResourceManager.GetString("fromLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login to another account.
        /// </summary>
        public static string gameManagerMenuItemLoginToAnotherAccountLabelContent {
            get {
                return ResourceManager.GetString("gameManagerMenuItemLoginToAnotherAccountLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string gameManagerMenuItemSettingsLabelContent {
            get {
                return ResourceManager.GetString("gameManagerMenuItemSettingsLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Games.
        /// </summary>
        public static string gamesLabelContent {
            get {
                return ResourceManager.GetString("gamesLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Game is uploaded.
        /// </summary>
        public static string gameUploadedLabelContent {
            get {
                return ResourceManager.GetString("gameUploadedLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Help.
        /// </summary>
        public static string helpMenuItemLabelContent {
            get {
                return ResourceManager.GetString("helpMenuItemLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About system.
        /// </summary>
        public static string helpMenuItemSystemInfoLabelContent {
            get {
                return ResourceManager.GetString("helpMenuItemSystemInfoLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Install.
        /// </summary>
        public static string installBtnLabelContent {
            get {
                return ResourceManager.GetString("installBtnLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Home.
        /// </summary>
        public static string libraryMenuItemHomeLabelContent {
            get {
                return ResourceManager.GetString("libraryMenuItemHomeLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Library.
        /// </summary>
        public static string libraryMenuLabelContent {
            get {
                return ResourceManager.GetString("libraryMenuLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Logout from account.
        /// </summary>
        public static string logoutLabelContent {
            get {
                return ResourceManager.GetString("logoutLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Next.
        /// </summary>
        public static string nextBtnContent {
            get {
                return ResourceManager.GetString("nextBtnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Office Ware - Offers.
        /// </summary>
        public static string offersDialogTitleContent {
            get {
                return ResourceManager.GetString("offersDialogTitleContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Play.
        /// </summary>
        public static string playBtnLabelContent {
            get {
                return ResourceManager.GetString("playBtnLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Player.
        /// </summary>
        public static string playerLabelContent {
            get {
                return ResourceManager.GetString("playerLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Profile.
        /// </summary>
        public static string profileMenuItemProfileLabelContent {
            get {
                return ResourceManager.GetString("profileMenuItemProfileLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Do you want to continue?.
        /// </summary>
        public static string requireContinueLabelContent {
            get {
                return ResourceManager.GetString("requireContinueLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        public static string saveBtnContent {
            get {
                return ResourceManager.GetString("saveBtnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Send request.
        /// </summary>
        public static string sendFriendRequestLabelContent {
            get {
                return ResourceManager.GetString("sendFriendRequestLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stats.
        /// </summary>
        public static string storeMenuItemStatsLabelContent {
            get {
                return ResourceManager.GetString("storeMenuItemStatsLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Store.
        /// </summary>
        public static string storeMenuLabelContent {
            get {
                return ResourceManager.GetString("storeMenuLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Can not upload game..
        /// </summary>
        public static string uploadGameErrorLabelContent {
            get {
                return ResourceManager.GetString("uploadGameErrorLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Uploading.
        /// </summary>
        public static string uploadingLabelContent {
            get {
                return ResourceManager.GetString("uploadingLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на View.
        /// </summary>
        public static string viewMenuItemLabelContent {
            get {
                return ResourceManager.GetString("viewMenuItemLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Player.
        /// </summary>
        public static string viewMenuItemPlayerLabelContent {
            get {
                return ResourceManager.GetString("viewMenuItemPlayerLabelContent", resourceCulture);
            }
        }
    }
}
